### ISSUE TITLE
CFC: Publish HTML Review Draft as W3C CR

### ISSUE THREAD

**Issue by LJWatson** [w3c/htmlwg#22]
This is a Call For Consensus (CFC) to publish the [January 2021 HTML Review Draft](https://html.spec.whatwg.org/review-drafts/2021-01/
) as a W3C Candidate Recommendation (CR).

[Wide review](https://github.com/w3c/htmlwg/issues/17
) was requested in July 2021. There were unresolved privacy concerns from the Privacy Interest Group (PING), and so the proposal is to include this non-normative statement to the CR.

>Notice: the (above / below) functionality hooks into the Reporting API, which is a not-yet-standardized work in progress at W3C and which has unresolved privacy-related discussions. Implementors are encouraged to follow these discussions and be aware that this functionality could change or be removed as those discussions progress.
>
>Changes made after the 2020 HTML Review Draft can be found in issue #17 [2]. 

If you support publication of the January 2021 HTML Review Draft as a W3C CR including the non-normative notice, add a thumbs up to this comment.

If you do not support publication, add a thumbs down to this comment and post a comment to let us know why.

If you do not respond to this CFC your support for the proposal will be assumed. This is not ideal, so please take a moment to let us know if you support the proposal or not.
 
Please respond to this CFC by the end of your day on Friday 14 January 2022.

**Comment by stevefaulkner** [comment]
I do not support publication as The document contains out of date advice around the use of headings and the semantics of headings (e.g. https://html.spec.whatwg.org/review-drafts/2021-01/#headings-and-sections) This has been the case for too many years.

**Comment by LJWatson** [comment]
@stevefaulkner could you point to the issues on the WHATWG HTML repo where these concerns have been raised? Thanks.

**Comment by stevefaulkner** [comment]
@LJWatson https://github.com/whatwg/html/issues/83

**Comment by patrickhlauke** [comment]
Agree with @stevefaulkner's objection - the outline algorithm is still, from what i can see, "aspirational" and lacks real-world support in browser/AT combinations, and at the very least this should be clearly signposted, rather than just stating it as if it was fact.

**Comment by MakotoUeki** [comment]
+1 to @stevefaulkner and @patrickhlauke.

**Comment by aardrian** [comment]
For the same reason as Steve and Pat. Now is as good a time as any (except the past, of course) to not support the publication to CR.

And @MakotoUeki , I think you have to give a thumbs-down as well as the comment. I _think_.

**Comment by domenic** [comment]
> If you support publication of the January 2021 HTML Review Draft as a W3C CR including the non-normative notice, add a thumbs up to this comment.

I do not support publication including this non-normative notice because doing so has been rejected already by the WHATWG editors in https://github.com/whatwg/html/issues/6933, so it will not be appearing in the Review Draft.

**Comment by stevefaulkner** [comment]
The WHATWG claims to reflect reality in it's HTML specification, it is abundantly clear that this is not the case in regards to the semantics of headings and sectioning elements. 10 years ago the false and misleading statements could have been viewed as aspirational, that views utility has long since passed. 
My objection pertains to misleading statements:
[4.3.3 The section element](https://html.spec.whatwg.org/multipage/sections.html#the-section-element)
> Notice how the use of section means that the author can use h1 elements throughout, without having to worry about whether a particular section is at the top level, the second level, the third level, and so on.

[4.3.7 The hgroup element](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element)
> The hgroup element represents the heading of a section, which consists of all the h1–h6 element children of the hgroup element. The element is used to group a set of h1–h6 elements when the heading has multiple levels, such as subheadings, alternative titles, or taglines.
>
> The rank of an hgroup element is the rank of the highest-ranked h1–h6 element descendant of the hgroup element, if there are any such elements, or otherwise the same as for an h1 element (the highest rank). Other h1–h6 elements of heading content in the hgroup element indicate subheadings or subtitles or (secondary) alternative titles.
> 
> The section on headings and sections defines how hgroup elements are assigned to individual sections.

> The point of using hgroup in these examples is to prevent the h2 element (which acts as a secondary title) from creating a separate section of its own in any outline and to instead cause the contents of the h2 to be shown in rendered output from the outline algorithm in some way to indicate that it is not the title of a separate section but instead just a secondary title in a group of titles.

> In both cases it is important to note the use of the hgroup element to group the two titles indicates that the titles are not equivalent; instead the first h1 gives the (primary) title while the second gives the (secondary) alternative title. Even though both the title and alternative title are marked up with h1 elements, in a rendered view of output from the outline algorithm, the second h1 in the hgroup will be shown in some way that clearly indicates it is secondary; for example:

[4.3.11 Headings and sections](https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections)

> The h1–h6 elements and the hgroup element are headings.

> The first element of heading content in an element of sectioning content represents the heading for that section. Subsequent headings of equal or higher rank start new (implied) sections, headings of lower rank start implied subsections that are part of the previous one. In both cases, the element represents the heading of the implied section.

> Sections may contain headings of any rank, but authors are strongly encouraged to either use only h1 elements, or to use elements of the appropriate rank for the section's nesting level.


Code examples in the following element definitions that perpetuate the falsehoods:
- [4.3.4 The nav element](https://html.spec.whatwg.org/multipage/sections.html#the-nav-element)
- [4.3.5 The aside element](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element)
- [4.3.2 The article element](https://html.spec.whatwg.org/multipage/sections.html#the-article-element)
- [4.3.3 The section element](https://html.spec.whatwg.org/multipage/sections.html#the-section-element)
- [4.3.7 The hgroup element](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element)
- [4.3.9 The footer element](https://html.spec.whatwg.org/multipage/sections.html#the-footer-element)
- [4.3.11 Headings and sections](https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections)
- [4.3.11.1 Creating an outline](https://html.spec.whatwg.org/multipage/sections.html#outlines)
- [4.3.11.2 Sample outlines](https://html.spec.whatwg.org/multipage/sections.html#sample-outlines)
- [4.3.12 Usage summary](https://html.spec.whatwg.org/multipage/sections.html#usage-summary-2) 

Once the HTML Specification is bought into line with the implementation reality in regards to the above TPGi will happily remove our objection to publication.

**Comment by LJWatson** [comment]
@domenic wrote:
>I do not support publication including this non-normative notice because doing so has been rejected already by the WHATWG editors in whatwg/html#6933, so it will not be appearing in the Review Draft.

The proposal is to add the informative note to the CR not to the Review Draft. Can you clarify if your objection is to the note being added to the Review Draft, or to the CR? Thanks.

**Comment by johnfoliot** [comment]
I will add my voice to the chorus of objections to this publication - as @stevefaulkner correctly notes, the current draft describes fantasy, not reality, with regard to headings, sectioning and hgroup. 

To requote [@sideshowbarker from 7 years ago](https://github.com/whatwg/html/issues/83#issuecomment-167461826), "**We’re here to solve existing real problems for real users** —not to hypothetically solve problems for some of them if we could somehow just get browser implementors to see things our way and implement what we’ve specced, or get AT vendors to fix their horribly broken/buggy tools."

**Comment by lauracarlson** [comment]
Agree with @stevefaulkner.

**Comment by domenic** [comment]
> The proposal is to add the informative note to the CR not to the Review Draft. Can you clarify if your objection is to the note being added to the Review Draft, or to the CR? Thanks.

The review draft *is* the CR, per the Memorandum of Understanding; they are both the same document, hosted at https://html.spec.whatwg.org/review-drafts/2021-01/ . The W3C does not publish separate CR documents.

**Comment by LJWatson** [comment]
>The review draft is the CR, per the Memorandum of Understanding; they are both the same document, hosted at 
https://html.spec.whatwg.org/review-drafts/2021-01/

The non-normative text is proposed based on our interpretation of clause 4.2c of the [MoU](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html):>The HTML WG shall explore techniques other than having a HTML or DOM specification with normative differences such as an extension specification; or as non-normative advice;

**Comment by domenic** [comment]
Facsinating. If your interpretation of that text is that you can modify WHATWG Review Drafts without editors merging the PRs, then I think that's an issue you should take up with the WHATWG Steering Group.

**Comment by domenic** [comment]
To be clear, my understanding of the intent of that clause when it was written is that the W3C is free to publish its own separate non-normative advice documents (e.g. [NOTE](https://www.w3.org/Consortium/Process/NOTE.html)s).

**Comment by michaelchampion** [comment]
As someone who helped negotiate https://www.w3.org/2019/04/WHATWG-W3C-MOU.html, my understanding is:
- @domenic is right, if the WHATWG editors and the W3C HTML WG can't find agreement, the next step is to escalate to the WHATWG SG.
- If all else fails but "the differences are not too entangled with the rest of the spec, the REC might be issued as the Review Draft plus a companion document."  I don't interpret the "companion document" as a non-normative NOTE, but an integral part of the normative Recommendation that describes a delta from the Review Draft.  That does take us toward the Bad Old Days of not having a single HTML standard, but does keep the vast majority of the content in sync and ensures that differences are principled rather than arbitrary.

**Comment by plehegar** [comment]
4.2.b is the applicable clause then, ie asking the WHATWG SG to step in. Makes sense to me.

**Comment by LJWatson** [comment]
With thanks to everyone who responded, this CFC closes with no support and two objections.

The next step will be to consider both objections with a view to finding a positive resolution in both cases.

**Comment by Tachi107** [comment]
Hi all, as the outline algorithm issue has been solved some time ago, are there any plans to publish one of the recent HTML review drafts as a W3C Candidate Recommendation?

Thank you all for your efforts.
